import { ref, computed, watch, onMounted, onBeforeUnmount } from 'vue';
import { adminEncyclopediaList, adminEncyclopediaDetail, adminEncyclopediaCreate, adminEncyclopediaUpdate, adminEncyclopediaDelete, adminEncyclopediaImage, adminEncyclopediaBatchImport } from '../../../api/index.js';
import { useUiStore } from '../../../stores/ui.js';
import PageHeader from '../../../shared/components/PageHeader.js';
import AppIcon from '../../../shared/components/AppIcon.js';
import AppLoading from '../../../shared/components/AppLoading.js';
import AppEmpty from '../../../shared/components/AppEmpty.js';
import AppError from '../../../shared/components/AppError.js';

const PAGE_SIZE = 12;
const CROPS = ['苹果','蓝莓','樱桃','玉米','葡萄','柑橘','桃','甜椒','马铃薯','覆盆子','大豆','南瓜','草莓','番茄','水稻','小麦'];
const CATEGORIES = ['真菌性病害','细菌性病害','病毒性病害','虫害','健康状态'];
const RISKS = ['低','中','高','严重'];
const blankSource = () => ({ title: '', url: '', organization: '' });
const blankForm = () => ({ class_en: '', name_cn: '', name_en: '', crop_cn: '', category: '', risk_level: '中', symptom_summary: '', epidemiology: '', pathogen: '', differentiation: '', symptoms: [''], prevention: [''], treatment: [''], sources: [blankSource()], image_url: '' });

export default {
  name: 'AdminEncyclopedia', components: { PageHeader, AppIcon, AppLoading, AppEmpty, AppError },
  setup() {
    const ui = useUiStore();
    const entries = ref([]), loading = ref(false), error = ref('');
    const search = ref(''), query = ref(''), filterCrop = ref(''), filterCategory = ref(''), filterRisk = ref('');
    const page = ref(1), total = ref(0), totalPages = ref(1);
    const modal = ref({ open: false, editing: null }), form = ref(blankForm()), errors = ref({}), saving = ref(false);
    const modelClasses = ref([]), classError = ref('');
    const imageFile = ref(null), imagePreview = ref('');
    const confirmDelete = ref(null), deleting = ref(false), deleteError = ref('');
    const importState = ref({ open: false, records: [], fileName: '', error: '', loading: false, preview: null, result: null });
    let timer, loadId = 0;
    const pageNumbers = computed(() => { const start = Math.max(1, Math.min(page.value - 2, totalPages.value - 4)); return Array.from({ length: Math.min(5, totalPages.value) }, (_, i) => start + i); });

    async function load() {
      const id = ++loadId; loading.value = true; error.value = '';
      try {
        const data = await adminEncyclopediaList({ q: query.value.trim(), crop: filterCrop.value, category: filterCategory.value, risk: filterRisk.value, page: page.value, page_size: PAGE_SIZE });
        if (id !== loadId) return;
        const list = Array.isArray(data) ? data : (data?.items || data?.entries || data?.list || []);
        entries.value = list; total.value = Number(Array.isArray(data) ? list.length : (data?.total ?? list.length)); totalPages.value = Math.max(1, Number(data?.pages || Math.ceil(total.value / PAGE_SIZE)));
        if (page.value > totalPages.value) { page.value = totalPages.value; return load(); }
      } catch (e) { if (id === loadId) { entries.value = []; total.value = 0; error.value = e.message || '百科词条加载失败'; } }
      finally { if (id === loadId) loading.value = false; }
    }
    watch(search, value => { clearTimeout(timer); timer = setTimeout(() => { query.value = value; page.value = 1; load(); }, 300); });
    watch([filterCrop, filterCategory, filterRisk], () => { page.value = 1; load(); });
    function goToPage(next) { next = Math.max(1, Math.min(next, totalPages.value)); if (next !== page.value) { page.value = next; load(); } }

    async function loadClasses() { try { const r = await fetch('/model-data/class_labels.json'); if (!r.ok) throw new Error(); modelClasses.value = await r.json(); } catch { classError.value = '模型类别加载失败，仍可暂不关联'; } }
    function clearPreview() { if (imagePreview.value) URL.revokeObjectURL(imagePreview.value); imagePreview.value = ''; imageFile.value = null; }
    const category = value => value === '健康' ? '健康状态' : (value || '');
    function openCreate() { clearPreview(); form.value = blankForm(); errors.value = {}; modal.value = { open: true, editing: null }; }
    async function openEdit(entry) {
      clearPreview(); errors.value = {}; modal.value = { open: true, editing: entry.id }; saving.value = true;
      try { const d = await adminEncyclopediaDetail(entry.id) || entry; form.value = { ...blankForm(), ...d, category: category(d.category), symptoms: d.symptoms?.length ? [...d.symptoms] : [''], prevention: d.prevention?.length ? [...d.prevention] : [''], treatment: d.treatment?.length ? [...d.treatment] : [''], sources: d.sources?.length ? d.sources.map(s => ({ ...blankSource(), ...s })) : [blankSource()] }; }
      catch (e) { ui.showToast(e.message || '详情加载失败', 'error'); modal.value.open = false; }
      finally { saving.value = false; }
    }
    function closeModal() { if (!saving.value) { clearPreview(); modal.value.open = false; } }
    function addItem(field) { form.value[field].push(field === 'sources' ? blankSource() : ''); }
    function removeItem(field, i) { form.value[field].splice(i, 1); if (!form.value[field].length) addItem(field); }
    function onClassChange() { const c = modelClasses.value.find(x => x.en === form.value.class_en); if (!c) return; if (!form.value.name_cn.trim()) form.value.name_cn = c.cn; if (!form.value.crop_cn) form.value.crop_cn = c.crop; if (!form.value.name_en.trim()) form.value.name_en = c.en.split('___').pop().replaceAll('_', ' '); if (c.disease === '健康' && !form.value.category) form.value.category = '健康状态'; }
    function onImageChange(e) { clearPreview(); const file = e.target.files?.[0]; if (file) { imageFile.value = file; imagePreview.value = URL.createObjectURL(file); } }
    const trimList = list => (list || []).map(x => String(x).trim()).filter(Boolean);
    function payload() { return { ...form.value, class_en: form.value.class_en.trim() || null, name_cn: form.value.name_cn.trim(), name_en: form.value.name_en.trim(), crop_cn: form.value.crop_cn.trim(), category: category(form.value.category), symptom_summary: form.value.symptom_summary.trim(), epidemiology: form.value.epidemiology.trim(), pathogen: form.value.pathogen.trim(), differentiation: form.value.differentiation.trim(), symptoms: trimList(form.value.symptoms), prevention: trimList(form.value.prevention), treatment: trimList(form.value.treatment), sources: form.value.sources.map(s => ({ title: s.title.trim(), url: s.url.trim(), organization: s.organization.trim() })).filter(s => s.title || s.url || s.organization) }; }
    function validate(d) { const e = {}; if (!d.name_cn) e.name_cn = '请输入中文名'; if (!d.crop_cn) e.crop_cn = '请选择作物'; if (!d.category) e.category = '请选择类别'; if (!d.symptom_summary) e.symptom_summary = '请输入简要描述'; if (!d.symptoms.length) e.symptoms = '至少填写一条症状'; const bad = d.sources.find(s => !s.title || (s.url && !/^https?:\/\//i.test(s.url))); if (bad) e.sources = !bad.title ? '来源必须填写标题' : '网址须以 http:// 或 https:// 开头'; errors.value = e; return !Object.keys(e).length; }
    async function save() { const d = payload(); if (!validate(d)) return; saving.value = true; try { const result = modal.value.editing ? await adminEncyclopediaUpdate(modal.value.editing, d) : await adminEncyclopediaCreate(d); const id = result?.id || modal.value.editing; if (imageFile.value && id) await adminEncyclopediaImage(id, imageFile.value); ui.showToast('保存成功', 'success'); saving.value = false; closeModal(); await load(); } catch (e) { ui.showToast(e.message || '保存失败', 'error'); } finally { saving.value = false; } }
    function askDelete(entry) { confirmDelete.value = entry; deleteError.value = ''; }
    async function doDelete() { if (!confirmDelete.value || deleting.value) return; deleting.value = true; deleteError.value = ''; try { await adminEncyclopediaDelete(confirmDelete.value.id); ui.showToast('已删除「' + confirmDelete.value.name_cn + '」', 'success'); confirmDelete.value = null; if (entries.value.length === 1 && page.value > 1) page.value--; await load(); } catch (e) { deleteError.value = e.message || '删除失败，请稍后重试'; } finally { deleting.value = false; } }

    function openImport() { importState.value = { open: true, records: [], fileName: '', error: '', loading: false, preview: null, result: null }; }
    async function onImportFile(e) { const file = e.target.files?.[0]; if (!file) return; const s = importState.value; s.fileName = file.name; s.error = ''; s.preview = s.result = null; try { const parsed = JSON.parse(await file.text()); s.records = Array.isArray(parsed) ? parsed : parsed.entries; if (!Array.isArray(s.records) || !s.records.length) throw new Error('JSON 应为非空数组，或包含 entries 数组'); } catch (err) { s.records = []; s.error = err.message || 'JSON 解析失败'; } }
    async function runImport(dryRun) { const s = importState.value; if (!s.records.length || s.loading) return; s.loading = true; s.error = ''; try { const result = await adminEncyclopediaBatchImport(s.records, dryRun); if (dryRun) s.preview = result; else { s.result = result; ui.showToast('批量导入完成', 'success'); await load(); } } catch (e) { s.error = e.message || '批量导入失败'; } finally { s.loading = false; } }
    const summary = r => ({ created: r?.created ?? 0, updated: r?.updated ?? 0, skipped: r?.skipped ?? 0, errors: r?.errors ?? [] });

    onMounted(() => { load(); loadClasses(); }); onBeforeUnmount(() => { clearTimeout(timer); clearPreview(); });
    return { entries, loading, error, search, filterCrop, filterCategory, filterRisk, page, total, totalPages, pageNumbers, modal, form, errors, saving, modelClasses, classError, imagePreview, confirmDelete, deleting, deleteError, importState, crops: CROPS, categories: CATEGORIES, risks: RISKS, load, goToPage, openCreate, openEdit, closeModal, addItem, removeItem, onClassChange, onImageChange, save, remove: askDelete, doDelete, openImport, onImportFile, runImport, summary };
  },
  template: `
  <div class="admin-encyclopedia">
    <page-header icon="book-open" title="百科管理" description="百科词条维护与模型类别关联"><div class="admin-encyclopedia-actions"><button class="btn btn-outline btn-sm" @click="openImport"><app-icon name="upload" :size="14"></app-icon> JSON 批量导入</button><button class="btn btn-primary btn-sm" @click="openCreate"><app-icon name="plus" :size="14"></app-icon> 新增词条</button></div></page-header>
    <div class="encyclopedia-toolbar admin-encyclopedia-toolbar"><div class="search-box"><span class="search-icon"><app-icon name="search" :size="15"></app-icon></span><input v-model="search" aria-label="搜索百科词条" placeholder="搜索名称或模型类别..." /></div><select class="form-select" v-model="filterCrop" aria-label="按作物筛选"><option value="">全部作物</option><option v-for="c in crops" :key="c">{{c}}</option></select><select class="form-select" v-model="filterCategory" aria-label="按分类筛选"><option value="">全部分类</option><option v-for="c in categories" :key="c">{{c}}</option></select><select class="form-select" v-model="filterRisk" aria-label="按风险筛选"><option value="">全部风险</option><option v-for="r in risks" :key="r">{{r}}</option></select></div>
    <div class="admin-list-summary" aria-live="polite">共 {{total}} 条词条 · 第 {{page}} / {{totalPages}} 页</div>
    <app-loading v-if="loading" text="加载百科数据..."></app-loading><app-error v-else-if="error" :message="error" :retryable="true" @retry="load"></app-error><app-empty v-else-if="!entries.length" icon="book-open" title="暂无符合条件的词条"></app-empty>
    <div v-else class="admin-encyclopedia-grid"><article v-for="e in entries" :key="e.id" class="card admin-encyclopedia-card"><div class="admin-entry-main"><div class="admin-entry-title">{{e.name_cn}} <span>{{e.name_en}}</span></div><div class="admin-entry-tags"><span class="tag tag-sm tag-crop">{{e.crop_cn||'-'}}</span><span class="tag tag-sm tag-category">{{e.category==='健康'?'健康状态':(e.category||'-')}}</span><span class="tag tag-sm">{{e.risk_level||'-'}}</span><span class="tag tag-sm" :class="e.class_en?'tag-linked':'tag-unlinked'">{{e.class_en?'已关联模型':'未关联模型'}}</span></div><code v-if="e.class_en" class="admin-class-label">{{e.class_en}}</code></div><div class="admin-entry-buttons"><button class="btn btn-sm btn-outline" :aria-label="'编辑'+e.name_cn" @click="openEdit(e)"><app-icon name="edit" :size="13"></app-icon></button><button class="btn btn-sm btn-danger" :aria-label="'删除'+e.name_cn" @click="remove(e)"><app-icon name="trash" :size="13"></app-icon></button></div></article></div>
    <nav v-if="!loading && !error && totalPages>1" class="encyclopedia-pagination" aria-label="百科管理分页"><button class="page-button page-nav" :disabled="page===1" @click="goToPage(page-1)">上一页</button><button v-for="n in pageNumbers" :key="n" class="page-button" :class="{active:page===n}" @click="goToPage(n)">{{n}}</button><button class="page-button page-nav" :disabled="page===totalPages" @click="goToPage(page+1)">下一页</button><span class="page-summary">共 {{total}} 条</span></nav>

    <div v-if="modal.open" class="modal-overlay" @click.self="closeModal"><div class="modal-dialog encyclopedia-form-dialog" role="dialog" aria-modal="true"><button class="modal-close" :disabled="saving" @click="closeModal"><app-icon name="x" :size="14"></app-icon></button><div class="modal-header"><div class="modal-icon"><app-icon name="book-open" :size="28"></app-icon></div><h2 class="modal-title">{{modal.editing?'编辑词条':'新增词条'}}</h2></div><div class="modal-body">
      <div class="form-group"><label class="form-label">模型类别关联</label><select class="form-select" v-model="form.class_en" @change="onClassChange"><option value="">暂不关联</option><option v-for="c in modelClasses" :key="c.en" :value="c.en">{{c.cn}} · {{c.en}}</option></select><small v-if="classError" class="form-error">{{classError}}</small><small v-else class="form-help">只自动补全当前为空的名称、作物和健康分类。</small></div>
      <div class="form-grid"><div class="form-group"><label class="form-label">中文名 *</label><input class="form-input" v-model="form.name_cn" /><small v-if="errors.name_cn" class="form-error">{{errors.name_cn}}</small></div><div class="form-group"><label class="form-label">英文名</label><input class="form-input" v-model="form.name_en" /></div><div class="form-group"><label class="form-label">作物 *</label><select class="form-select" v-model="form.crop_cn"><option value="" disabled>请选择</option><option v-for="c in crops" :key="c">{{c}}</option></select><small v-if="errors.crop_cn" class="form-error">{{errors.crop_cn}}</small></div><div class="form-group"><label class="form-label">类别 *</label><select class="form-select" v-model="form.category"><option value="" disabled>请选择</option><option v-for="c in categories" :key="c">{{c}}</option></select><small v-if="errors.category" class="form-error">{{errors.category}}</small></div><div class="form-group"><label class="form-label">风险等级</label><select class="form-select" v-model="form.risk_level"><option v-for="r in risks" :key="r">{{r}}</option></select></div></div>
      <div class="form-group"><label class="form-label">简要描述 *</label><textarea class="form-textarea" v-model="form.symptom_summary" rows="2"></textarea><small v-if="errors.symptom_summary" class="form-error">{{errors.symptom_summary}}</small></div><div class="form-grid"><div class="form-group"><label class="form-label">发病规律</label><textarea class="form-textarea" v-model="form.epidemiology" rows="3"></textarea></div><div class="form-group"><label class="form-label">病原 / 诱因</label><textarea class="form-textarea" v-model="form.pathogen" rows="3"></textarea></div></div><div class="form-group"><label class="form-label">鉴别要点</label><textarea class="form-textarea" v-model="form.differentiation" rows="2"></textarea></div>
      <div v-for="field in [{key:'symptoms',label:'症状表现 *'},{key:'prevention',label:'预防措施'},{key:'treatment',label:'治疗方法'}]" :key="field.key" class="form-group"><label class="form-label dynamic-label">{{field.label}}<button class="btn btn-sm btn-outline" @click="addItem(field.key)">+ 添加</button></label><div v-for="(v,i) in form[field.key]" :key="field.key+i" class="dynamic-row"><input class="form-input" v-model="form[field.key][i]" /><button class="btn btn-sm btn-outline remove-row" @click="removeItem(field.key,i)">×</button></div><small v-if="errors[field.key]" class="form-error">{{errors[field.key]}}</small></div>
      <div class="form-group"><label class="form-label dynamic-label">资料来源<button class="btn btn-sm btn-outline" @click="addItem('sources')">+ 添加来源</button></label><div v-for="(s,i) in form.sources" :key="'source'+i" class="source-editor"><input class="form-input" v-model="s.title" placeholder="来源标题" /><input class="form-input" v-model="s.organization" placeholder="发布机构" /><input class="form-input source-url" v-model="s.url" type="url" placeholder="https://..." /><button class="btn btn-sm btn-outline remove-row" @click="removeItem('sources',i)">×</button></div><small v-if="errors.sources" class="form-error">{{errors.sources}}</small></div>
      <div class="form-group"><label class="form-label">百科图片</label><input type="file" accept="image/*" @change="onImageChange" /><div v-if="imagePreview||form.image_url" class="admin-image-preview"><img :src="imagePreview||form.image_url" alt="百科图片预览" /><span>{{imagePreview?'待上传图片预览':'当前图片'}}</span></div></div><div class="modal-actions"><button class="btn btn-primary" :disabled="saving" @click="save">{{saving?'保存中...':'保存'}}</button><button class="btn btn-outline" :disabled="saving" @click="closeModal">取消</button></div>
    </div></div></div>

    <div v-if="confirmDelete" class="modal-overlay" @click.self="!deleting&&(confirmDelete=null)"><div class="modal-dialog confirm-dialog" role="alertdialog"><div class="modal-header"><div class="modal-icon"><app-icon name="alert-triangle" :size="28"></app-icon></div><h2 class="modal-title">确认删除</h2><p class="modal-subtitle">确定删除「{{confirmDelete.name_cn}}」吗？此操作不可恢复。</p></div><div class="modal-body"><p v-if="deleteError" class="inline-error">{{deleteError}}</p><div class="modal-actions centered"><button class="btn btn-danger" :disabled="deleting" @click="doDelete">{{deleting?'删除中...':'确认删除'}}</button><button class="btn btn-outline" :disabled="deleting" @click="confirmDelete=null">取消</button></div></div></div></div>

    <div v-if="importState.open" class="modal-overlay" @click.self="!importState.loading&&(importState.open=false)"><div class="modal-dialog import-dialog" role="dialog"><button class="modal-close" :disabled="importState.loading" @click="importState.open=false"><app-icon name="x" :size="14"></app-icon></button><div class="modal-header"><div class="modal-icon"><app-icon name="upload" :size="28"></app-icon></div><h2 class="modal-title">JSON 批量导入</h2><p class="modal-subtitle">先试运行检查，再明确确认应用。</p></div><div class="modal-body"><input type="file" accept="application/json,.json" @change="onImportFile" /><p v-if="importState.fileName" class="form-help">{{importState.fileName}} · {{importState.records.length}} 条记录</p><p v-if="importState.error" class="inline-error">{{importState.error}}</p><div v-if="importState.preview" class="import-summary"><strong>试运行结果</strong><span>新增 {{summary(importState.preview).created}}</span><span>更新 {{summary(importState.preview).updated}}</span><span>跳过 {{summary(importState.preview).skipped}}</span><span>错误 {{summary(importState.preview).errors.length}}</span><ul v-if="summary(importState.preview).errors.length"><li v-for="(e,i) in summary(importState.preview).errors" :key="i">{{typeof e==='string'?e:JSON.stringify(e)}}</li></ul></div><div v-if="importState.result" class="import-summary success"><strong>正式导入结果</strong><span>新增 {{summary(importState.result).created}}</span><span>更新 {{summary(importState.result).updated}}</span><span>跳过 {{summary(importState.result).skipped}}</span><span>错误 {{summary(importState.result).errors.length}}</span></div><div class="modal-actions"><button class="btn btn-outline" :disabled="!importState.records.length||importState.loading" @click="runImport(true)">{{importState.loading?'处理中...':'试运行预览'}}</button><button class="btn btn-primary" :disabled="!importState.preview||importState.loading||!!importState.result" @click="runImport(false)">确认应用</button></div></div></div></div>
  </div>`
};